### ISSUE TITLE
labels and milestones

### ISSUE THREAD

**Issue by rusakovprz** [rusakovprz/smc#5]
Разработать систему меток и этапов.

Сисема меток должна:
- [x] делить все задачи на группы (обычные задачи, ошибки, тестирование, документация)
- [x] группы должны содержать более мелкую детализацию (по критичности, приоритетам)
- [x] группы должны быть обьеденины градациями основных цветов (градации красного, градации желтого и т.д.) 

коды цветоых меток можно посмотреть [здесь](http://colorbrewer2.org/)

Система этапов должна определять основные этапы работы по проекту (макет, разработка, тестирование, документирование)

**Comment by rusakovprz** [comment]
Предложения по меткам:

| Название метки | Name label | Color code | Color example |
| --- | --- | --- | --- |
| **Красная группа** |  |  |  |
| Ошибка | bug | #ff0f1f |  |
| Горячее исправление | hot fix | #b60205 |  |
| Блокирует | blocked | #ff0000 |  |
| **Зелёная группа** |  |  |  |
| Задача | issue | #0e8a16 |  |
| Организационная/инфраструктурная | issue | #10bf50 |  |
| Улучшение | enhancement | #0eff06 |  |
| Рефакторинг | refactoring | #1aff26 |  |
| **Синяя группа** |  |  |  |
| Тестирование | test | #84b6eb |  |
| Документация | doc | #0052cc |  |
| **Фиолетовая группа** |  |  |  |
| Требуется помощь | help wanted | #b405f9 |  |
| Вопрос обсуждение | question | #cc317c |  |
| **Желтая группа** | Дополнительная |  |  |
| Повтор | duplicate | #ffff04 |  |
| Не подтверждено | invalid | #ffbb04 |  |
| Не будет исправлено | wontfix | #ff5500 |  |

**Comment by rusakovprz** [comment]
Предложения по "системе этапов":
- Базовый функционал (первый этап, проектирование, разработка, переработка)
- Горячие исправления (Объединяет по времени все этапы, собирает критичиские ошибки, требующие немедленного устранения)
- Тестирование (Всё что найдено во время тестирования)
- Развитие (может быть несколько итераций, последующие улучшения функционала, рефакторинг, оптимизация, устранение найденных ошибок во время эксплуатации)

**Comment by rusakovprz** [comment]
Done.
